### ISSUE TITLE
please a mini tutorial  how to make it to new Versions working

### ISSUE THREAD

**Issue by Liriel-666** [dfint/df-steam-hook#18]
please a mini tutorial  how to make it to new Versions working

**Comment by insolor** [comment]
We can't add such a tutorial, because for now adding support of new versions needs at least basic reverse engineering skills, so it wouldn't be a **_mini_** tutorial by any means.

I'm working on a tool to simplify the process (see #17), but it's not ready yet.

**Comment by insolor** [comment]
Actually, this is not possible. I've implemented [CLI tool](https://github.com/dfint/df-steam-hook/tree/main/tools), and it works on 50.08, but it finds only some patterns on experimental branch of DF, so I assume that it will work more or less the same on the future DF versions.
