### ISSUE TITLE
add Linux suport?

### ISSUE THREAD

**Issue by malacration** [dfint/df-steam-hook#33]
Could this project have a Linux build?

**Comment by insolor** [comment]
See https://github.com/dfint/df-steam-hook-rs. But it is in work-in-progress state a the time.

**Comment by malacration** [comment]
Is it not possible to build c++ on Linux?

**Comment by insolor** [comment]
No, it depends on [detours](https://github.com/microsoft/Detours) library, which is windows-only.

**Comment by malacration** [comment]
thanks for answer!
